Updated to read the api key and api user from the taskrc
fplourde/Taskwarrior-habitica-hooks pull request #10
Opened 2017-11-03 14:36 UTC by ksonney

This changes the scripts to use taskw and read the habitica keys from the .taskrc. It no longer requires the user to modify the scripts themselves, but it does require Taskwarrior API v2 now.

2018-10-24 15:31 UTC, fplourde commented
Thank you for your support

2018-10-24 15:32 UTC, fplourde requested changes
Update the link and I will merge the request.

Thank you for your support

2018-10-24 15:32 UTC, fplourde commented on README.md
> +	wget https://github.com/ksonney/Taskwarrior-habitica-hooks/archive/master.zip
Do not link to a different project. Make the modification and I will merge the code.

2018-10-25 05:56 UTC, fplourde approved these changes

2018-10-25 05:56 UTC, merged

2018-10-25 13:21 UTC, ksonney commented
Awesome! You updated it before I saw the emails, so all good!